/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
/**
 *
 * @author M S I
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    ContentPanel contentPanel = new ContentPanel();

    public AdminGUI() {
        FlatIntelliJLaf.setup();
        initComponents();

        ClassGradePanel classGradePanel = new ClassGradePanel();
        currentPanel.add(classGradePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        closeProgramBtn = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        classGradeTab = new javax.swing.JButton();
        studentTab = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        subjectTab = new javax.swing.JButton();
        schoolYearTab = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutTab = new javax.swing.JButton();
        currentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1200, 650));
        setState(600);

        header.setBackground(new java.awt.Color(85, 169, 253));

        closeProgramBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        closeProgramBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeProgramBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeProgramBtn.setText("X");
        closeProgramBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeProgramBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeProgramBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeProgramBtnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(1227, Short.MAX_VALUE)
                .addComponent(closeProgramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeProgramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        sidebar.setBackground(new java.awt.Color(85, 169, 253));
        sidebar.setForeground(new java.awt.Color(102, 153, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 600));

        classGradeTab.setBackground(new java.awt.Color(85, 169, 253));
        classGradeTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        classGradeTab.setForeground(new java.awt.Color(255, 255, 255));
        classGradeTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ClassGradeTabIcon.png"))); // NOI18N
        classGradeTab.setText("LỚP - KHỐI LỚP");
        classGradeTab.setBorder(null);
        classGradeTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classGradeTab.setFocusPainted(false);
        classGradeTab.setFocusable(false);
        classGradeTab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        classGradeTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classGradeTabMouseClicked(evt);
            }
        });
        classGradeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classGradeTabActionPerformed(evt);
            }
        });

        studentTab.setBackground(new java.awt.Color(85, 169, 253));
        studentTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentTab.setForeground(new java.awt.Color(255, 255, 255));
        studentTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/student.png"))); // NOI18N
        studentTab.setText("HỌC SINH");
        studentTab.setBorder(null);
        studentTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentTab.setFocusPainted(false);
        studentTab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentTabActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(85, 169, 253));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/teacher.png"))); // NOI18N
        jButton6.setText("GIÁO VIÊN");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(85, 169, 253));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ClassGradeTabIcon.png"))); // NOI18N
        jButton7.setText("KẾT QUẢ");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        subjectTab.setBackground(new java.awt.Color(85, 169, 253));
        subjectTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subjectTab.setForeground(new java.awt.Color(255, 255, 255));
        subjectTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/subject.png"))); // NOI18N
        subjectTab.setText("MÔN HỌC");
        subjectTab.setBorder(null);
        subjectTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subjectTab.setFocusPainted(false);
        subjectTab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subjectTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectTabMouseClicked(evt);
            }
        });
        subjectTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTabActionPerformed(evt);
            }
        });

        schoolYearTab.setBackground(new java.awt.Color(85, 169, 253));
        schoolYearTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        schoolYearTab.setForeground(new java.awt.Color(255, 255, 255));
        schoolYearTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolYear.png"))); // NOI18N
        schoolYearTab.setText("NĂM HỌC");
        schoolYearTab.setBorder(null);
        schoolYearTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        schoolYearTab.setFocusPainted(false);
        schoolYearTab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        schoolYearTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schoolYearTabMouseClicked(evt);
            }
        });
        schoolYearTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolYearTabActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/SchoolLogo.png"))); // NOI18N

        logoutTab.setBackground(new java.awt.Color(85, 169, 253));
        logoutTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutTab.setForeground(new java.awt.Color(255, 255, 255));
        logoutTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Logout.png"))); // NOI18N
        logoutTab.setText("ĐĂNG XUẤT");
        logoutTab.setBorder(null);
        logoutTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutTab.setFocusPainted(false);
        logoutTab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutTab.setPreferredSize(new java.awt.Dimension(127, 50));
        logoutTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classGradeTab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(subjectTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schoolYearTab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(classGradeTab)
                .addGap(18, 18, 18)
                .addComponent(subjectTab)
                .addGap(18, 18, 18)
                .addComponent(schoolYearTab, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        currentPanel.setBackground(new java.awt.Color(255, 255, 255));
        currentPanel.setPreferredSize(new java.awt.Dimension(1050, 550));
        currentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Tắt chương trình
    private void closeProgramBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeProgramBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeProgramBtnMouseClicked

    private void closeProgramBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeProgramBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_closeProgramBtnMouseEntered

    private void classGradeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classGradeTabActionPerformed

        ClassGradePanel classGradePanel = new ClassGradePanel();

        currentPanel.removeAll();
        currentPanel.repaint();
        currentPanel.revalidate();
        currentPanel.add(classGradePanel);
        currentPanel.repaint();
        currentPanel.revalidate();
    }//GEN-LAST:event_classGradeTabActionPerformed

    private void subjectTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectTabMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTabMouseClicked

    private void schoolYearTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolYearTabMouseClicked
        // TODO add your handling code here:
        SchoolYearPanel schoolYearPanel = new SchoolYearPanel();

        currentPanel.removeAll();
        currentPanel.repaint();
        currentPanel.revalidate();
        currentPanel.add(schoolYearPanel);
        currentPanel.repaint();
        currentPanel.revalidate();
    }//GEN-LAST:event_schoolYearTabMouseClicked

    private void schoolYearTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolYearTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolYearTabActionPerformed

    private void classGradeTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classGradeTabMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_classGradeTabMouseClicked

    private void subjectTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTabActionPerformed

        SubjectPanel subjectPanel = new SubjectPanel();
        currentPanel.removeAll();
        currentPanel.repaint();
        currentPanel.revalidate();
        currentPanel.add(subjectPanel);
        currentPanel.repaint();
        currentPanel.revalidate();
    }//GEN-LAST:event_subjectTabActionPerformed

    private void studentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentTabActionPerformed

        StudentPanel studentPanel = new StudentPanel();

        currentPanel.removeAll();
        currentPanel.repaint();
        currentPanel.revalidate();
        currentPanel.add(studentPanel);
        currentPanel.repaint();
        currentPanel.revalidate();
    }//GEN-LAST:event_studentTabActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TeacherPanel teacherPanel = new TeacherPanel();

        currentPanel.removeAll();
        currentPanel.repaint();
        currentPanel.revalidate();
        currentPanel.add(teacherPanel);
        currentPanel.repaint();
        currentPanel.revalidate();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ResultPanel resultPanel = new ResultPanel();

        currentPanel.removeAll();
        currentPanel.repaint();
        currentPanel.revalidate();
        currentPanel.add(resultPanel);
        currentPanel.repaint();
        currentPanel.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void logoutTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutTabActionPerformed
        // TODO add your handling code here:
        new LoginGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton classGradeTab;
    private javax.swing.JLabel closeProgramBtn;
    private javax.swing.JPanel currentPanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutTab;
    private javax.swing.JButton schoolYearTab;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton studentTab;
    private javax.swing.JButton subjectTab;
    // End of variables declaration//GEN-END:variables
}
