/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author M S I
 */
public class StudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentPanel
     */
    public StudentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentTabbedPane = new javax.swing.JTabbedPane();
        studentPanel = new javax.swing.JPanel();
        ethnicPanel = new javax.swing.JPanel();
        religionPanel = new javax.swing.JPanel();
        classErollmentPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1050, 600));

        studentTabbedPane.setPreferredSize(new java.awt.Dimension(1050, 600));

        studentPanel.setBackground(new java.awt.Color(153, 153, 0));
        studentPanel.setPreferredSize(new java.awt.Dimension(1050, 600));

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        studentTabbedPane.addTab("Học sinh", studentPanel);

        ethnicPanel.setBackground(new java.awt.Color(204, 255, 0));
        ethnicPanel.setPreferredSize(new java.awt.Dimension(1050, 600));

        javax.swing.GroupLayout ethnicPanelLayout = new javax.swing.GroupLayout(ethnicPanel);
        ethnicPanel.setLayout(ethnicPanelLayout);
        ethnicPanelLayout.setHorizontalGroup(
            ethnicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ethnicPanelLayout.setVerticalGroup(
            ethnicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        studentTabbedPane.addTab("Dân tộc", ethnicPanel);

        religionPanel.setBackground(new java.awt.Color(0, 51, 51));
        religionPanel.setPreferredSize(new java.awt.Dimension(1050, 600));

        javax.swing.GroupLayout religionPanelLayout = new javax.swing.GroupLayout(religionPanel);
        religionPanel.setLayout(religionPanelLayout);
        religionPanelLayout.setHorizontalGroup(
            religionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        religionPanelLayout.setVerticalGroup(
            religionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        studentTabbedPane.addTab("Tôn giáo", religionPanel);

        classErollmentPanel.setBackground(new java.awt.Color(204, 204, 255));
        classErollmentPanel.setPreferredSize(new java.awt.Dimension(1050, 600));

        javax.swing.GroupLayout classErollmentPanelLayout = new javax.swing.GroupLayout(classErollmentPanel);
        classErollmentPanel.setLayout(classErollmentPanelLayout);
        classErollmentPanelLayout.setHorizontalGroup(
            classErollmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        classErollmentPanelLayout.setVerticalGroup(
            classErollmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        studentTabbedPane.addTab("Phân lớp", classErollmentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel classErollmentPanel;
    private javax.swing.JPanel ethnicPanel;
    private javax.swing.JPanel religionPanel;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JTabbedPane studentTabbedPane;
    // End of variables declaration//GEN-END:variables
}
