/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.SubjectBUS;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DTO.Subject;

/**
 *
 * @author M S I
 */
public class SubjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubjectPanel
     */
    SubjectBUS subjectBUS = new SubjectBUS();

    public SubjectPanel() {
        initComponents();
        loadDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSubjectID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCoefficient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSubjectName = new javax.swing.JTextField();
        txtNumberOfLesson = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectList = new javax.swing.JTable();
        addSubjectBtn = new javax.swing.JButton();
        editSubjectBtn = new javax.swing.JButton();
        deleteSubjectBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1050, 600));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1050, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 169, 253));
        jLabel1.setText("Quản lý môn học");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 169, 253));
        jLabel2.setText("Mã môn học");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 169, 253));
        jLabel3.setText("Hệ số");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 169, 253));
        jLabel4.setText("Tên môn học");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 169, 253));
        jLabel5.setText("Số tiết");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 169, 253));
        jLabel6.setText("Danh sách môn học");

        subjectList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã môn học", "Tên môn học", "Hệ số", "Số tiết"
            }
        ));
        subjectList.setRowHeight(30);
        subjectList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjectList);

        addSubjectBtn.setBackground(new java.awt.Color(85, 169, 253));
        addSubjectBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSubjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/addIcon.png"))); // NOI18N
        addSubjectBtn.setText("Thêm");
        addSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectBtnActionPerformed(evt);
            }
        });

        editSubjectBtn.setBackground(new java.awt.Color(85, 169, 253));
        editSubjectBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        editSubjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/editIcon.png"))); // NOI18N
        editSubjectBtn.setText("Sửa");
        editSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubjectBtnActionPerformed(evt);
            }
        });

        deleteSubjectBtn.setBackground(new java.awt.Color(85, 169, 253));
        deleteSubjectBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteSubjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/delete.png"))); // NOI18N
        deleteSubjectBtn.setText("Xóa");
        deleteSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSubjectBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(85, 169, 253));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/clearIcon.png"))); // NOI18N
        clearBtn.setText("Mới");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(editSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(deleteSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(142, 142, 142)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNumberOfLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jLabel1)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumberOfLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubjectBtn)
                    .addComponent(editSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Môn học", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) subjectList.getModel();
        model.setRowCount(0); // xóa table 
        for (Subject subject : subjectBUS.getAllSubjects()) {
            Object dataRow[] = new Object[4];
            dataRow[0] = subject.getSubjectID();
            dataRow[1] = subject.getSubjectName();
            dataRow[2] = subject.getCoefficient();
            dataRow[3] = subject.getNumberOfLesson();
            model.addRow(dataRow);
            System.out.println(subject.toString());
        }
        

    }

    public boolean validateForm() {
        if (txtSubjectID.getText().isEmpty() || txtSubjectName.getText().isEmpty() || txtCoefficient.getText().isEmpty() || txtNumberOfLesson.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public void setModel(Subject subject) {
        txtSubjectID.setText(subject.getSubjectID());
        txtSubjectName.setText(subject.getSubjectName());
        txtCoefficient.setText(subject.getCoefficient() + "");
        txtNumberOfLesson.setText(subject.getNumberOfLesson() + "");
    }

    public Subject getModel() {
        Subject subject = new Subject();
        subject.setSubjectID(txtSubjectID.getText());
        subject.setSubjectName(txtSubjectName.getText());
        subject.setCoefficient(Integer.parseInt(txtCoefficient.getText()));
        subject.setNumberOfLesson(Integer.parseInt(txtNumberOfLesson.getText()));
        return subject;
    }

    public void reset() {
        txtSubjectID.setText("");
        txtSubjectName.setText("");
        txtCoefficient.setText("");
        txtNumberOfLesson.setText("");
    }

    private void addSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectBtnActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            Subject subject = getModel();
            if(subjectBUS.addSubject(subject)) {
                JOptionPane.showMessageDialog(this, "Thêm môn học thành công");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_addSubjectBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void editSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubjectBtnActionPerformed
        // TODO add your handling code here:
        if(validateForm()) {
            Subject subject = getModel();
            if (subjectBUS.editSubject(subject)) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }  
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }

    }//GEN-LAST:event_editSubjectBtnActionPerformed

    private void deleteSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSubjectBtnActionPerformed
        // TODO add your handling code here:
        Subject subject = getModel();
        if(subjectBUS.deleteSubject(subject)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadDataTable();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_deleteSubjectBtnActionPerformed

    private void subjectListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectListMouseClicked
        // TODO add your handling code here:
        int row = subjectList.rowAtPoint(evt.getPoint());
        String subjectID = subjectList.getValueAt(row, 0).toString();
        Subject subject = subjectBUS.getSubjectByID(subjectID);
        setModel(subject);
        
    }//GEN-LAST:event_subjectListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteSubjectBtn;
    private javax.swing.JButton editSubjectBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable subjectList;
    private javax.swing.JTextField txtCoefficient;
    private javax.swing.JTextField txtNumberOfLesson;
    private javax.swing.JTextField txtSubjectID;
    private javax.swing.JTextField txtSubjectName;
    // End of variables declaration//GEN-END:variables
}
